### ISSUE TITLE
Error on Drag and drop

### ISSUE THREAD

**Issue by YanYas** [vvvvpm/vpm#3]
I tried draggin and dropping vpacks on the vpm.exe program but it coughed up the following error:

```
Found a VVVV in registry.
Parsing input Pack
Something went wrong:
'>' is an unexpected token. The expected token is '='. Line 49, position 89.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, S
tring expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean prese
rveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at vpm.VpmUtils.ParseAndValidateXmlFile(String xmlfile)
   at vpm.Program.Main(String[] args)
Temp folder created successfully:
C:\Users\H\Desktop\vvvv\.vpm
Removing vpm temp folder.
Press any key to exit...
```

any ideas what it could be?

Also, how would one find and download packages from cmd line?

**Comment by microdee** [comment]
thanks for sending output, can you send me the file or link you tried to
use? it looks like something was wrong with the xml on line 49.

2016-08-17 6:12 GMT+02:00 YanYas notifications@github.com:

**Comment by YanYas** [comment]
Hi David,

I tried a few and they all came back with the same error. The file was
downloaded via my browser and dragged onto a registered copy of vpm.exe.
That vpm folder is inside a folder called plugins, inside my vvvv root
folder.

The xml looks alright.

Side Note:
I just tried with links I found on the blog page
https://vvvv.org/blog/introducing-vpm-a-vvvv-package-manager and it seems
more sucessful.
I see that to build the packages I need to have Visual Studio installed
(its something I think you should mention in your documentation). I use
Sharp Develop because VS takes up too much space for my relatively small
harddrive. 12GBs seemed over kill just for a compiler in my case. Do you
think there could be a workaround for this?

Thinking in terms of other users who just want to use packs reliably but
don't necessarily want to go down the out of full-on plugin development, I
think they may be turned off by having to download VS despite the
considerable convience of installing packages properly.

**Comment by microdee** [comment]
hmmm that's odd, I'll have a look when I get to a place where I can use my
laptop, until then use vpm(s):// links.
about vs issue: yeah I can totally understand it, I recently promoted a pc
to my home server so I will probably do automated nightly builds on it for
common packs built from source so one can avoid installing visual studio.
